# Generated by Django 5.2.2 on 2025-06-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroGanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('plataforma', models.CharField(max_length=100)),
                ('corridas', models.PositiveIntegerField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promocoes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gorjeta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
