# Generated by Django 5.2.2 on 2025-06-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
